@baseUrl = http://localhost:4004
@servicePath = /products

//GET {{baseUrl}}{{servicePath}}/Products

# POST {{baseUrl}}{{servicePath}}/Products
# Content-Type: application/json

# {
#     "sku": "SKU-PROD-99",
#     "name": "Wireless Mechanical Keyboard",
#     "price": 89.99,
#     "stock": 50,
#     "category_ID": "e0ba0603-a979-4566-a365-8b301c2b53f6"
# }

# POST {{baseUrl}}{{servicePath}}/Products
# Content-Type: application/json

# {
#     "sku": "SKU-PROD-VALID1",
#     "name": "Invalid Price Product",
#     "price": -10.00,
# }

# POST {{baseUrl}}{{servicePath}}/Products
# Content-Type: application/json

# {
#     "sku": "INVALID_SKU_FORMAT",
#     "name": "Invalid SKU Product",
#     "price": 29.99,
#     "stock": 15,
#     "category_ID": "{{categoryWithProductsId}}"
# }

POST {{baseUrl}}{{servicePath}}/Products
Content-Type: application/json

{
    "sku": "SKU-00100",
    "productName": "Mechanical Keyboard",
    "price": 89.99,
    "stock": 50,
    "category_ID": "4f1a4de1-96cd-4d89-9b98-ea48690b22f2"
}