GET http://localhost:4004/university/Courses?$filter=departmentCode eq 'CS' and semester eq 1

GET http://localhost:4004/university/Students?$filter=cgpa gt 8.0

 POST http://localhost:4004/university/Enrollments
 Content-Type: application/json

 {
     "studentId": "00000000-0000-0000-0000-000000000001",
     "courseCode": "CS101",
     "enrollmentDate": "2026-05-30",
     "status": "Enrolled",
     "attendancePercent": 100.0
 }

GET http://localhost:4004/university/Enrollments?$filter=studentId eq 00000000-0000-0000-0000-000000000001

GET http://localhost:4004/university/Courses?$filter=currentEnrolled lt maxStudents

 PATCH http://localhost:4004/university/Enrollments(studentId=00000000-0000-0000-0000-000000000001,courseCode='CS101')
 Content-Type: application/json

 {
     "grade": "A",
     "gradePoints": 4.0,
     "status": "Completed"
 }
